### PR TITLE
SM prior code update

### PR DESCRIPTION
**Pull request by RaT0M**
I tried to include all your last comments @TonioF from last pull request #3.

- Connection to the platform:
  - get_mean_state_vector function is now included.
  - state vector and covariance matrix are returned.
- The relative paths in the tests like you sugested (with `../path/to/config/or/auxdata`) did not work for me (_pytest root directory_ was set to `prior-engine/` ... maybe theres the difference in test initiation?)

@TonioF you mentioned having more comments on the last pull request. Can you recall your thouths?

About tagging..should we provide a single tag for the entire prior engine or do you @JorisTimmermans  manage the versioning?

@TonioF  and @JorisTimmermans I would be happy about comments on the change and overall direction of my progress to assure that I'm moving in the right direction..

### CODE REVIEW

**Comment by RaT0M** [comment]
sorry for the old commits showing up again..

**Comment by TonioF** [comment]
Hi Thomas,
sorry for the chaos with the tests. I found that putting them into a similarly named package does not work well, as then Python cannot distinguish between these two packages and might produce errors. the best solution then is to leave the name of the main package as is ('multiply_prior_engine') and to take the  'multiply_' from the name of the test package (i.e., 'prior_engine'). The issue with the dots was due to the configuration of my nose tests, your configuration is actually correct.

Other things I came across: 
- You are using explicit references to specific priors in the prior engine class ('if p[:2] == 'sm':', line 93). We should see to avoid such, as the adding of a new prior would require to make changes to the prior engine. For the moment, we can leave it in, as it is not a pressing issue and we need to find a good solution for this. Maybe we can talk about this at the coding workshop.
- The method named calc() does not seem to calculate anything but rather initialize the prior for further use. The method should then be named accordingly, otherwise it becomes confusing.
- There are some lines with commented code scattered across the code. If you don't need them anymore, remove them. If you might still need them later, write a comment why you leave them out for now.

**Comment by TonioF** [comment]
There should be single tag for the prior engine repository AND Joris should manage this.

About the overall direction ... I think @JorisTimmermans and probably also @jgomezdans should see whether the prior engine delivers what they expect.

**Comment by RaT0M** [comment]
Hi,
thank you for your comments, @TonioF  :thumbsup: 
Now:
- Changed folder structure. The structural issues with the tests should be fixed by now.
- Changed `calc()` is now `initialize()`
- Added documentation

Still:
- TODO remove unwanted commented code
- TODO discuss explicit loading of 'sm' config and hence prior configuration file

**Pull request merged**
