### PR TITLE
Merge new master and changes in user prior creator & prior framework

### PR DESCRIPTION
**Pull request by RaT0M**
Here the recent changes @JorisTimmermans and @TonioF made (mostly to vegetationpriorcreator) are integrated with the previous pr #31 .

Tests are failing because the lai files are missing in the repo. Could you please add these, @JorisTimmermans ?

Can we merge the changes concerning *framework* and *user prior creator*?

### CODE REVIEW

**Comment by RaT0M** [comment]
the builds are failing in master anyways due to the same missing file problem.

**Comment by TonioF** [comment]
Okay, I'll see to merge these branches

**Comment by RaT0M** [comment]
@TonioF: I don't want to waste your time, I) can totally do it. I just wanted to know if every one is fine with adding the changes to the master branch.

**Comment by TonioF** [comment]
@RaT0M : We need to be careful here. I have just merged the merge_new_master_user_framework-branch and pushed the result to the master in the multiply repository. The main reasoning behind this was that I did not want ot have these separate branches diverge to the point where we couldn't merge them anymore. Hope that no big issues arise from this ...

**Comment by RaT0M** [comment]
> We need to be careful here. I have just merged the merge_new_master_user_framework-branch and pushed the result to the master in the multiply repository.

Ah, ..then I misunderstood the commit message. I thought it was saying something of *merge_RaT0M:master..* or so.. hence, i was thinking that you merged my fork's master.

> The main reasoning behind this was that I did not want ot have these separate branches diverge to the point where we couldn't merge them anymore. 

That's exactly why I also wanted to finally merge these changes.. :+1: 

Anyway, finally all merged and I guess all is fine.. what do you mean with:
> Hope that no big issues arise from this ...

Working on single branches per feature would alleviate merging of these big changes. That's a field I definitely can work on.

**Comment by TonioF** [comment]
I meant that I hope I did not introduce confusion as we have been simultaneously trying to merge everything into the master branch. But apparently it's all fine now, so that's good.

**Pull request merged**
